### ISSUE TITLE
Fonts don't load on Manjaro

### ISSUE THREAD

**Issue by kenballus** [nh-server/fusee-interfacee-tk#11]
This is a great tool; thanks for making it.

Running the latest binary on a fresh Manjaro install gives the following errors:
`Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf`

A screenshot:
![image](https://user-images.githubusercontent.com/49924171/89325380-b2971a00-d656-11ea-8823-112ad85b67a2.png)

Using the script does not have this problem.

**Comment by noirscape** [comment]
Your fontconfig file isn't properly set up. This isn't a fusee bug.

Please reference [the Arch wiki](https://wiki.archlinux.org/index.php/Font_configuration) for more on how to fix it or try to fix this issue on the [Manjaro forums](https://forum.manjaro.org/).

**Comment by Oreo639** [comment]
I'm confused. Was this an issue with your fontconfig? It seems like the version of fontconfig bundled with v1.0.1 is too old to support modern font confs.

(Just a note, the v1.0.0 version was built with a newer fontconfig so it should work just fine for you)

**Comment by sczther** [comment]
Happens on latest Fedora too

**Comment by noirscape** [comment]
Again this is not a fusee bug.

This is a bug with how your distros are handling fontconfigs cache.

Don't report it here.

**Comment by Inotamira** [comment]
> Again this is not a fusee bug.
> 
> This is a bug with how your distros are handling fontconfigs cache.
> 
> Don't report it here.

If I'm looking at everything correctly, it's either an issue with ttk.style at line 32 in app.py, or it's an issue with tkinter.feildialogue, as these seem to be having issues parsing fonts correctly in Arch. You aren't wrong, it's not an issue with your app directly, but you're also not being helpful as you're not really looking into the issue and claiming it as an issue with fontconfig, when it isn't as the method fonts are called in Arch changed recently. A solution may simply be to use a different style method, but I haven't had a chance to properly go over how ttk.style or tkinter.feildialogue handles fonts as you may be able to simply change how you call it to solve the problem, but likely tkinter needs an update to confirm to the new font configuration method.

**Comment by marianomacchi** [comment]
I was having the same issue on Fedora 32.

I couldn't solve it by removing fontconfig's cache, but I managed to by cloning the repository and directly running the app.py as a python script (after having installed pyusb).

**Comment by dixiedream** [comment]
In order to use (Python 3.8) i cloned the source code and run through command line:

### Requirements
`pip install pyusb`

`# pacman -S tk` as it wasn't installed on my arch machine.

### Usage
`python app.py`

**Comment by ThisNekoGuy** [comment]
Can confirm that installing `python-pyusb` and `tk` via pacman and running `app.py `directly works just fine.
If I had to guess, the dependencies being bundled with the binary might be outdated; it definitely isn't the distro's fault.

**Comment by Ammako** [comment]
Doesn't really make sense to maintain an AUR release for a version that specifically doesn't correctly work on Aech, doesn't it?

**Comment by Oreo639** [comment]
The issue is that pyinstaller bundles libfontconfig.
The only change between 1.0.0 and 1.0.1 is the libraries bundled in it.

The best solution is probably to not use pyinstaller imo.

**Comment by Ammako** [comment]
Here's a PKBUILD that makes more sense.

https://github.com/Ammako/fusee-interfacee-tk/releases/tag/PKGBUILD
