### ISSUE TITLE
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)?

### ISSUE THREAD

**Issue by ebiak** [nh-server/fusee-interfacee-tk#9]
i'm trying to run the program in linux (Pop!_os 19.10) and im getting this error:
`usb.core.USBError: [Errno 13] Access denied (insufficient permissions)`(this  isn't the entire error but other than this there aren't any errors just locations)
so what does this mean and what am i supposed to do?

**Comment by Oreo639** [comment]
You have to run it as root.

You can also follow this to set up the necessary udev rules so you don't need root 
https://nh-server.github.io/switch-guide/extras/adding_udev/

**Comment by ebiak** [comment]
that didn't launch the payload this is the output and it seems like it has been successful but nothing shows up on the screen:
'Identified a Linux system; setting up the appropriate backend.
Found a Tegra with Device ID: b'\x80\x05\x03\x18\x00\x00\x00\x0c\xc8\x07-d\x01\x10\x10b'

Setting ourselves up to smash the stack...
Uploading payload...
Smashing the stack...
skipping checks
The USB device stopped responding-- sure smells like we've smashed its stack. :)
Launch complete!
'

**Comment by ebiak** [comment]
found a solution! i think because my laptop's usb 3 port is connected to a built-in usb hub it used ehci drivers,what i had to do was run [this](https://gist.github.com/DavidBuchanan314/41b12362cc4d8c539dc441d75155f2e9) script and then it patched my ehci driver and i could inject the payload
